### ISSUE TITLE
Tensor flow 1.5 not working

### ISSUE THREAD

**Issue by parisni** [jtourille/yaset#1]
Hi

Apparently, installing the tool installs tensorflow 1.5. However it seems only 1.3 version works right now:    

    2018-02-14 11:22:47.389799: F tensorflow/python/lib/core/bfloat16.cc:664] Check failed: PyBfloat16_Type.tp_base != nullptr 

Thanks

**Comment by jtourille** [comment]
Thank you for raising this issue.
The bug is resolved in commit a21d138882f179e4c6ceb4288cc7dfb33c29e09e.
I added a specific version requirement for tensorflow and updated the documentation accordingly.
