### ISSUE TITLE
loading wor2vec binary format & gensim 3.3

### ISSUE THREAD

**Issue by parisni** [jtourille/yaset#2]
I am using gensim 3.3
I built a wor2vec binary format.
I had error while loading the file.
This looked related to https://github.com/RaRe-Technologies/gensim/issues/1882
I changed model.wv.* to model.* as proposed in the issued above in the wor2vec.py python file

**Comment by jtourille** [comment]
Thanks for spotting this issue. I added a version requirement for gensim (3.2.0). I will work on a _per-version_ fix later (using model.wv* or model.* depending on the gensim version).
